"""update novelist name property to unique

Revision ID: e6a2fa399692
Revises: f82a55d9377a
Create Date: 2025-07-23 13:45:35.282748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a2fa399692'
down_revision: Union[str, Sequence[str], None] = 'f82a55d9377a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'novelists', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'novelists', type_='unique')
    # ### end Alembic commands ###
