"""add state field to account model

Revision ID: f82a55d9377a
Revises: d729d55002e7
Create Date: 2025-07-15 08:21:14.459459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82a55d9377a'
down_revision: Union[str, Sequence[str], None] = 'd729d55002e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    state_enum = sa.Enum('enabled', 'disabled', name='state', create_type=False)
    state_enum.create(op.get_bind())
    op.add_column('accounts', sa.Column('state', state_enum, server_default='enabled', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'state')
    state_enum = sa.Enum('enabled', 'disabled', name='state', create_type=False)
    state_enum.drop(op.get_bind())
    # ### end Alembic commands ###
