name: Book's Collection

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened]


jobs:
  unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Python 3.13
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install poetry
              run: pipx install poetry

            - name: Install project deps
              run: poetry install

            - name: Run tests
              run: poetry run task test
              env:
                DATABASE_URL: ${{secrets.DATABASE_URL}}
                SECRET_KEY: ${{secrets.SECRET_KEY}}
                ALGORITHM: ${{secrets.ALGORITHM}}
                TOKEN_TIME_EXPIRATION_SECS: ${{secrets.TOKEN_TIME_EXPIRATION_SECS}}
